# Configuración mínima para master.sh
# Edita según necesites
PARALLEL=4
# Rutas de repos (relativas a este repo)
REPOS=(amd64 arm64)

# Proxmox API settings
# URL del API (incluye protocolo y puerto): https://proxmox.example.com:8006
PM_API_URL="https://pve1.dialmaweb.com"
# API token format: user@realtokenidm!=secret
# Ejemplo: PVEAPITOKEN="root@pam!mytoken=abcdef123456"
PVEAPITOKEN="root@pve!root=fe746c11-f20c-4e09-8cae-0793ac03f601"
